version: "3"
services:
  node:
    container_name: novel_node
    image: node:16-alpine3.11
    working_dir: /usr/src/app
    ports:
      - 8083:8080
    volumes:
      - ./app/:/usr/src/app/
    tty: true # これしないとすぐにexitedになる。
  nginx:
    container_name: novel_nginx
    image: nginx
    ports:
      - 8082:80
    volumes:
      - ./app/public/:/usr/share/nginx/html/
    depends_on:
      - node
